l2l/config/routes.rb
Rails.application.routes.draw do
  # This line mounts Spree's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to
  # Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the
  # :at option to something different.
  #
  # We ask that you don't use the :as option here, as Spree relies on it being
  # the default of "spree".
  mount Spree::Core::Engine, at: '/spree'


  root to: 'v1/products#index'
  # API version1
  api_version(:module => "V1",:default => true, :header => {:name => "Accept", :value => "application/vnd.mycompany.com; version=1"}) do
    resources :user_usages, only: [] do
      collection do
        post 'video_usage' => 'user_usages#create_video_usage'
        get 'topics/:topic_id/video_usage/:video_id' => 'user_usages#video_usage'
      end
    end
    get '/get_user_details' => 'base#get_user_details'
    get '/set_redirect_url_after_login' => 'base#set_redirect_url_after_login'
    post '/add_user_preference' => 'base#add_user_preference'
    # post '/upload_user_note' => 'base#upload_user_note'
    resources :user_data_upload, only: [] do
      collection do
        post '/upload_user_note' => 'user_data_upload#upload_user_note'
        post '/update_user_note' => 'user_data_upload#update_user_note'
        post '/sharing_note_mail' => 'user_data_upload#sharing_note_mail'
        get '/retrive_user_notes' => 'user_data_upload#retrive_user_notes'
      end
    end
    resources :orders, only: [] do
      member do
        post 'charge'
      end
      collection do
        get 'payment'
        get 'order_history'
      end
    end
    resources :products, only: [:index, :show] do
      collection do
        get 'my_subjects'        
      end
      member do
        get 'chapters_and_sections'
        get "topics/:section_id" => 'products#topics'
        get 'complete_toc'
      end
    end
    resources :cart_items do
      collection do
        delete 'clear_cart'
        delete 'remove_grade'
      end
    end

    resources :learning_paths, only: [:create] do
      collection do
        get 'my_status'
        delete 'delete_path'
      end
    end

    # Quiz data
    get '/quiz/data/:id' => 'contents#quiz_data'
    # Content routes
    get 'contents/:content_type/:id' => 'contents#content_data'
  end
  # frontend interface to view details of workers and jobs of resque
  resque_web_constraint = lambda { |request| request.remote_ip == '127.0.0.1' }
  constraints resque_web_constraint do
    mount ResqueWeb::Engine => "/resque_web"
  end

  # all devise related routes are below (start)
  devise_for :users, controllers: {
                       omniauth_callbacks: 'users/omniauth_callbacks',
                       sessions: 'users/sessions',
                       confirmations: 'users/confirmations',
                       passwords: 'users/passwords',
                       unlocks: 'users/unlocks',
                       registrations: 'users/registrations'
                   }

  devise_scope :user do
    get "users/sign_out" => "devise/sessions#destroy"
  end
  # devise routes (end)

  resources :home, only: [] do
    collection do
      get 'welcome'
      get 'profile'
    end
  end

  # Swagger api
  resources :apidocs, only: [:index]
end

l2l/app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:welcome]
  def welcome
    render 'welcome', layout: false 
  end

  def profile
  end
end

l2l/app/views/home/index.html.haml
- content_for :top_content do
  .jumbotron
    .container
      %h1 Welcome!
      %p Register to get started.
      %p
        = link_to 'Register', new_user_registration_path, class: 'btn btn-primary btn-lg'

l2l/app/views/home/profile.html.haml
.container
  %p Welcome #{current_user.username}
  =link_to 'SIGN OUT', users_sign_out_path

l2l/app/views/home/welcome.html.erb
<% cache do %>
  <!DOCTYPE html>
  <html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>L2L</title>
    <link href="/assets/bootstrap.min.css" rel="stylesheet">
    <link href="/assets/main.scss" rel="stylesheet" type="text/css">
    <script src="/assets/jquery.js"></script>
    <script src="/assets/bootstrap.js"></script>
    <script src="/assets/header.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans|Roboto:300,400,400i,500,500i,700" rel="stylesheet">
  </head>
  <body>
  <div style="background: url(<%= asset_path('backgroundImage1.png')%>);position: relative;height: 1176px;"></div>
  <div class="container-fluid container-padding main-content">
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header page-scroll">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="true">
            <span class="sr-only">Toggle navigation</span>
            Menu <i class="fa fa-bars"></i>
          </button>
          <!--<a class="navbar-brand" href="index.html"><img class="img-responsive" src="images/scentruc_logo_white.svg"/></a>-->
          <a class="navbar-brand" href="index.html"><%= image_tag 'scentruc_logo_white.svg', class:"img-responsive"%></a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="navbar-collapse collapse in" id="bs-example-navbar-collapse-1" aria-expanded="true">
          <ul class="nav navbar-nav navbar-right navlist-center">
            <li>
              <a href="index.html">CURRICULUM</a>
            </li>
            <li>
              <a href="about.html">SUBSCRIPTION</a>
            </li>
            <li>
            <% if current_user.present? %>
              <a href="/users/sign_out">SIGN OUT</a>
            <%else %>
              <a href="/users/sign_in">SIGN IN</a>
            <% end %>
            </li>
            <li>
              <a href="/users/sign_up">SIGN UP FREE</a>
            </li>
          </ul>
        </div>
        <!-- /.navbar-collapse -->
      </div>
      <!-- /.container -->
    </nav>
    <!--<div style="background: url('images/backgroundImage1.png');position: relative;height: 1176px;"></div>-->
  </div>
  </body>
  </html>
<% end %>